[package]
name = "KobwebREVAMP"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
env_logger = "0.11.9"
io = "0.0.2"
log = "0.4.29"
mlua = {  version = "0.11", features = ["lua54", "async"]}

